#!/bin/bash

# A master script for recoloring my applications
# Maintainer: Ben Buchanan (https://github.com/Nynergy)

xrdb load .Xresources

pkill dunst

gen-dunst.sh
gen-polybar.sh
gen-zathura.sh

i3-msg restart
