" Configuration file for vim

" Maintainer:       Ben Buchanan
" Version:          1.1.0
" Last Modified:    02-Nov-2025

" COLORS
set background=dark
set t_Co=256
colo apparition
syntax on

" PATH & MENUS
set path+=**
set wildmenu
set wildignorecase

" TABS & INDENTS
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab

" MISC
set number relativenumber cursorline
set nohlsearch
set nocompatible
set backupcopy=yes

" CUSTOM COMMANDS
nnoremap c* *Ncgn
map ` <C-A>
map g` g<C-A>
nnoremap <leader>b :buffers<CR>:b<space>

" CUSTOM BINDINGS
map <silent> <F4> :setlocal spell!<CR>
map <silent> <F7> :Lexplore<CR>
nnoremap <leader>qq :confirm qall<CR>

" NETRW
let g:netrw_liststyle = 3
let g:netrw_banner = 0
"let g:netrw_browse_split = 4
"let g:netrw_altv = 1
let ghregex='\(^\|\s\s\)\zs\.\S\+'
let g:netrw_list_hide=ghregex
let g:netrw_fastbrowse = 0
let g:netrw_preview = 1
let g:netrw_winsize = -30

" STATUSLINE
set laststatus=2

set statusline=
set statusline+=%#Conceal#
set statusline+=\ %t
set statusline+=\ %m%r%h
set statusline+=\ %=
set statusline+=\ %#StatusLineFileType#
set statusline+=\ %Y
set statusline+=\ %#StatusLineFilePosition#
set statusline+=\ %(%4l,%-3c%)
set statusline+=\ %#StatusLineFilePercentage#
set statusline+=\ %3P\ 
