#!/bin/bash

# A startup script for connecting to the BU Domain via openconnect

SCRIPT=${0##*/}
PROTOCOL=pulse
USERNAME=$1
REALM='BU Domain Users'
SERVER=ssl.binghamton.edu

function printUsage() {
    printf '%s\n'   "$SCRIPT: connect to ssl.binghamton.edu via openconnect"
    printf '%s\n\n' "Usage: $SCRIPT <username>"
    printf '%s\n\n' '    <username>: the username you use to log in with CAS'
    printf '%s\n'   'You will be prompted for your password and 2FA token when invoked'
}

function killVPN() {
    pkill openconnect > /dev/null 2>&1 && notify-send "VPN ($SCRIPT)" "Disconnected from '$SERVER'"
    sleep 1
}

[ $# -ne 1 ] && { echo "Usage: $SCRIPT <username>"; exit; }

case $1 in
    -h|--help)
        printUsage;
	exit;;
    -k|--kill)
        killVPN;
	exit;;
esac

printf  "Please enter the password for '$USERNAME': "
read -s PASSWD

printf "\nPlease enter your 2FA token: "
read TOKEN
printf "\n"

{ echo "$PASSWD"; echo "$TOKEN"; } | openconnect -q -b --protocol=$PROTOCOL --authgroup="$REALM" -u $USERNAME --passwd-on-stdin $SERVER
sleep 1

ifconfig tun0 > /dev/null 2>&1 && notify-send "VPN ($SCRIPT)" "Connected to '$REALM' at '$SERVER'" \
                               || notify-send "VPN ($SCRIPT)" "Could not connect to '$SERVER'"
