#!/bin/bash

# A custom locker using i3lock

# Take a screenshot
#scrot /tmp/current.png

# Add blur to the screenshot
#convert -blur 0x4 /tmp/current.png /tmp/blur.png

# Add overlay to the blurred image
# composite -gravity southwest "$OVERLAY" /tmp/blur.png /tmp/lock.png

# Lock screen
BACKGROUND="$(grep color0 ~/.Xresources | awk '{print $2}')"
i3lock -c "$BACKGROUND"

#i3lock -i /tmp/blur.png
