#!/bin/bash

# A script for choosing and applying colorschemes to .Xresources

FONT="xos4Terminus-10"
BACKGROUND="$(grep color0 ~/.Xresources | awk '{print $2}')"
FOREGROUND="$(grep color8 ~/.Xresources | awk '{print $2}')"

DMENU_SETTINGS="-nb $BACKGROUND -nf $FOREGROUND -sb $FOREGROUND -sf $BACKGROUND -fn $FONT"

SCHEME_DIR="$HOME/.config/colorschemes"

getSchemes() {
    SCHEMES="$(echo "$(ls "$SCHEME_DIR")")"
    if [ -z "$SCHEMES" ]; then
        dunstify "ERROR WHEN CHOOSING SCHEME" "Could not read schemes from $SCHEME_DIR!"
        exit
    fi
}

getChoice() {
    CHOICE="$(echo -e "\n$SCHEMES" | dmenu -c -l 30 -bw 2 $DMENU_SETTINGS -i -p 'Choose a Scheme:')"
    if [ -z "$CHOICE" ]; then
        dunstify "ERROR WHEN CHOOSING SCHEME" "User did not pick a valid scheme!"
        exit
    fi
}

getColors() {
    BLACK="$(grep color0: "$SCHEME_DIR"/"$CHOICE" | awk '{print $2}' | sed 's/#//')"
    RED="$(grep color1: "$SCHEME_DIR"/"$CHOICE" | awk '{print $2}' | sed 's/#//')"
    GREEN="$(grep color2: "$SCHEME_DIR"/"$CHOICE" | awk '{print $2}' | sed 's/#//')"
    YELLOW="$(grep color3: "$SCHEME_DIR"/"$CHOICE" | awk '{print $2}' | sed 's/#//')"
    BLUE="$(grep color4: "$SCHEME_DIR"/"$CHOICE" | awk '{print $2}' | sed 's/#//')"
    MAGENTA="$(grep color5: "$SCHEME_DIR"/"$CHOICE" | awk '{print $2}' | sed 's/#//')"
    CYAN="$(grep color6: "$SCHEME_DIR"/"$CHOICE" | awk '{print $2}' | sed 's/#//')"
    WHITE="$(grep color7: "$SCHEME_DIR"/"$CHOICE" | awk '{print $2}' | sed 's/#//')"
    OFFWHITE="$(grep color8: "$SCHEME_DIR"/"$CHOICE" | awk '{print $2}' | sed 's/#//')"
}

setColors() {
    # BLACK
    sed -i "s/color0:\t#[0-9a-z]*/color0:\t#$BLACK/g" "$HOME"/.Xresources
    sed -i "s/background:\t#[0-9a-z]*/background:\t#$BLACK/g" "$HOME"/.Xresources
    sed -i "s/background: \[75\]#[0-9a-z]*/background: \[75\]#$BLACK/g" "$HOME"/.Xresources

    # RED
    sed -i "s/color1:\t#[0-9a-z]*/color1:\t#$RED/g" "$HOME"/.Xresources
    sed -i "s/color9:\t#[0-9a-z]*/color9:\t#$RED/g" "$HOME"/.Xresources

    # GREEN
    sed -i "s/color2:\t#[0-9a-z]*/color2:\t#$GREEN/g" "$HOME"/.Xresources
    sed -i "s/color10:\t#[0-9a-z]*/color10:\t#$GREEN/g" "$HOME"/.Xresources

    # YELLOW
    sed -i "s/color3:\t#[0-9a-z]*/color3:\t#$YELLOW/g" "$HOME"/.Xresources
    sed -i "s/color11:\t#[0-9a-z]*/color11:\t#$YELLOW/g" "$HOME"/.Xresources

    # BLUE
    sed -i "s/color4:\t#[0-9a-z]*/color4:\t#$BLUE/g" "$HOME"/.Xresources
    sed -i "s/color12:\t#[0-9a-z]*/color12:\t#$BLUE/g" "$HOME"/.Xresources

    # MAGENTA
    sed -i "s/color5:\t#[0-9a-z]*/color5:\t#$MAGENTA/g" "$HOME"/.Xresources
    sed -i "s/color13:\t#[0-9a-z]*/color13:\t#$MAGENTA/g" "$HOME"/.Xresources

    # CYAN
    sed -i "s/color6:\t#[0-9a-z]*/color6:\t#$CYAN/g" "$HOME"/.Xresources
    sed -i "s/color14:\t#[0-9a-z]*/color14:\t#$CYAN/g" "$HOME"/.Xresources

    # WHITE
    sed -i "s/foreground:\t#[0-9a-z]*/foreground:\t#$WHITE/g" "$HOME"/.Xresources
    sed -i "s/cursorColor:\t#[0-9a-z]*/cursorColor:\t#$WHITE/g" "$HOME"/.Xresources
    sed -i "s/color7:\t#[0-9a-z]*/color7:\t#$WHITE/g" "$HOME"/.Xresources
    sed -i "s/color15:\t#[0-9a-z]*/color15:\t#$WHITE/g" "$HOME"/.Xresources

    # OFFWHITE
    sed -i "s/color8:\t#[0-9a-z]*/color8:\t#$OFFWHITE/g" "$HOME"/.Xresources
}

getSchemes
getChoice
getColors
setColors

# Run master recolor script to set changes
prism
