#!/bin/bash

# A script for storing current .Xresources colors in a colorscheme file
# Maintainer: Ben Buchanan (https://github.com/Nynergy)

FONT="xos4Terminus-10"
BACKGROUND="$(grep color0 ~/.Xresources | awk '{print $2}')"
FOREGROUND="$(grep color4 ~/.Xresources | awk '{print $2}')"

DMENU_SETTINGS="-nb $BACKGROUND -nf $FOREGROUND -sb $FOREGROUND -sf $BACKGROUND -fn $FONT"

SCHEME_DIR="$HOME/.config/colorschemes"

getColors() {
    CONTENT="$(head -n 37 "$HOME"/.Xresources)"
    if [ -z "$CONTENT" ]; then
        dunstify "ERROR WHEN SAVING SCHEME" "Could not read $HOME/.Xresources!"
        exit
    fi
}

getSchemes() {
    SCHEMES="$(echo "$(ls "$SCHEME_DIR")" )"
    if [ -z "$SCHEMES" ]; then
        dunstify "ERROR WHEN SAVING SCHEME" "Could not read schemes from $SCHEME_DIR!"
        exit
    fi
}

getFilename() {
    FILENAME="$(echo -e "\n$SCHEMES" | dmenu -c -l 20 $DMENU_SETTINGS -i -p 'Scheme Name:')"
    if [ -z "$FILENAME" ]; then
        dunstify "ERROR WHEN SAVING SCHEME" "User did not provide a scheme name!"
        exit
    fi
}

saveColors() {
    MATCHES="$(echo -e "$SCHEMES" | grep "$FILENAME")"
    if [ -z "$MATCHES" ]; then
        echo -e "$CONTENT" > "$SCHEME_DIR/$FILENAME"
    else
        dunstify "ERROR WHEN SAVING SCHEME" "Colorscheme $FILENAME already exists!"
    fi
}

getColors
getSchemes
getFilename
saveColors
