#!/usr/bin/env bash

# A script for choosing and applying colorschemes to .Xresources

# Maintainer:       Ben Buchanan
# Version:          2.0.0
# Last Modified:    06-Jun-2026

XRESOURCES=$HOME/.Xresources

FONT="Terminus-10"
BACKGROUND=$(awk '/color0:/ {print $2}' "$XRESOURCES")
FOREGROUND=$(awk '/color8:/ {print $2}' "$XRESOURCES")

DMENU_SETTINGS=(-nb "$BACKGROUND" -nf "$FOREGROUND" \
                -sb "$FOREGROUND" -sf "$BACKGROUND" \
                -fn "$FONT")

SCHEME_DIR="$HOME/.config/colorschemes"

getSchemes() {
    SCHEMES="$(ls -1 "$SCHEME_DIR")"
    if [ -z "$SCHEMES" ]; then
        dunstify "ERROR WHEN CHOOSING SCHEME" "Could not read schemes from $SCHEME_DIR!"
        exit
    fi
}

getChoice() {
    CHOICE="$(echo -e "\n$SCHEMES" | dmenu -l 30 "${DMENU_SETTINGS[@]}" -i -p 'Choose a Scheme:')"
    if [ -z "$CHOICE" ]; then
        dunstify "ERROR WHEN CHOOSING SCHEME" "User did not pick a valid scheme!"
        exit
    fi
}

getColors() {
    declare -aG COLORS

    FOREGROUND=$(awk '/foreground:/ {print $2}' "$SCHEME_DIR/$CHOICE")
    BACKGROUND=$(awk '/background:/ {print $2}' "$SCHEME_DIR/$CHOICE")
    OPACITY=$(awk '/opacity:/ {print $2}' "$SCHEME_DIR/$CHOICE")
    local i
    for i in {0..15}; {
        COLORS[i]=$(awk -v pattern="color$i:" '$0 ~ pattern {print $2}' "$SCHEME_DIR/$CHOICE")
    }
}

setColors() {
    local pattern replace

    pattern='foreground:\t#[0-9a-z]*'; replace="foreground:\t$FOREGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/g" "$XRESOURCES"
    pattern='cursorColor:\t#[0-9a-z]*'; replace="cursorColor:\t$FOREGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/g" "$XRESOURCES"
    pattern='background:\t#[0-9a-z]*'; replace="background:\t$BACKGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/g" "$XRESOURCES"
    pattern='background: \[.*\]#[0-9a-z]*'; replace="background: $OPACITY"
    sed -i --follow-symlinks "s/$pattern/$replace/g" "$XRESOURCES"

    local i
    for i in {0..15}; {
        local color=${COLORS[$i]}
        pattern="color$i:\t#[0-9a-z]*"; replace="color$i:\t$color"
        printf 's/%s/%s/g\n' "$pattern" "$replace"
        sed -i --follow-symlinks "s/$pattern/$replace/g" "$XRESOURCES"
    }
}

getSchemes
getChoice
getColors
setColors

# Run master recolor script to set changes
prism
