#!/usr/bin/env bash

# A script for choosing and applying colorschemes to .Xresources

# Maintainer:       Ben Buchanan
# Version:          3.1.0
# Last Modified:    10-Jun-2026

XRESOURCES=$HOME/.Xresources

FONT="Terminus-10"
BACKGROUND=$(awk '/background:/ {print $2}' "$XRESOURCES" | head -n 1)
FOREGROUND=$(awk '/color8:/ {print $2}' "$XRESOURCES")

DMENU_SETTINGS=(-nb "$BACKGROUND" -nf "$FOREGROUND" \
                -sb "$FOREGROUND" -sf "$BACKGROUND" \
                -fn "$FONT")

SCHEME_DIR="$HOME/.config/rimeglass/colorschemes"

die() {
    dunstify 'ERROR' "$1"
    exit 1
}

getSchemes() {
    SCHEMES="$(ls -1 "$SCHEME_DIR")"
    [[ -z "$SCHEMES" ]] && die "Could not read schemes from '$SCHEME_DIR'"
}

getChoice() {
    CHOICE="$(echo -e "\n$SCHEMES" | dmenu -l 30 "${DMENU_SETTINGS[@]}" -i -p 'Choose a Scheme:')"
    [[ -z "$CHOICE" ]] && exit 0
}

getColors() {
    declare -aG COLORS

    FOREGROUND=$(awk '/foreground:/ {print $2}' "$SCHEME_DIR/$CHOICE")
    BACKGROUND=$(awk '/background:/ {print $2}' "$SCHEME_DIR/$CHOICE")
    OPACITY=$(awk '/opacity:/ {print $2}' "$SCHEME_DIR/$CHOICE")
    local i
    for i in {0..15}; {
        COLORS[i]=$(awk -v pattern="color$i:" '$0 ~ pattern {print $2}' "$SCHEME_DIR/$CHOICE")
    }
}

setColors() {
    local pattern replace

    pattern='foreground:\t#[0-9a-z]*'; replace="foreground:\t$FOREGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/g" "$XRESOURCES"
    pattern='cursorColor:\t#[0-9a-z]*'; replace="cursorColor:\t$FOREGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/g" "$XRESOURCES"
    pattern='background:\t#[0-9a-z]*'; replace="background:\t$BACKGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/g" "$XRESOURCES"
    pattern='background: \[.*\]#[0-9a-z]*'; replace="background: $OPACITY"
    sed -i --follow-symlinks "s/$pattern/$replace/g" "$XRESOURCES"

    local i color
    for i in {0..15}; {
        color=${COLORS[$i]}
        pattern="color$i:\t#[0-9a-z]*"; replace="color$i:\t$color"
        sed -i --follow-symlinks "s/$pattern/$replace/g" "$XRESOURCES"
    }
}

getSchemes
getChoice
getColors
setColors

# Run master recolor script to set changes
prism
