#!/usr/bin/env bash

# A script that prints disk info for polybar

# Maintainer:       Ben Buchanan
# Version:          1.0.1
# Last Modified:    10-Jun-2026

XRESOURCES=$HOME/.Xresources

NORMAL=$(awk '/color7:/ {print $2}' "$XRESOURCES")
FILLED=$(awk '/color4:/ {print $2}' "$XRESOURCES")

PERCENTAGE=$(df -h | awk '/\/$/ {sub(/%/,""); print $5}')

BLOCKS=$((PERCENTAGE / 10)) # This truncates the resulting float to an integer
(( BLOCKS == 10 )) && BLOCKS=9

BAR="%{F$FILLED}"

for (( i = 0; i < BLOCKS; i++ )); {
    BAR="$BAR-"
}

BAR="$BAR%{F$NORMAL}|"

for (( j = 0; j < 9 - BLOCKS; j++ )); {
    BAR="$BAR-"
}

printf '%s\n' "$BAR"
