#!/usr/bin/env bash

# (Is)sue (Li)ster :: 'isli'
# A script for tracking issues

# Maintainer:       Ben Buchanan
# Version:          1.1.1
# Last Modified:    10-Jun-2026

## Track issues in the terminal
##
## Usage: $0 [OPTIONS] [BASE_DIR]
##
## Options:
##   -h, --help                 Show this usage output
##   -v, --version              Show the version of the script
##   -n <DESC>, --new <DESC>    Create a new issue with description <DESC>
##   -a, --all                  List all tasks, regardless of status
##   -o <INDEX>, --open <INDEX> Open task with <INDEX> in $EDITOR

SCRIPT="${BASH_SOURCE[0]##*/}"

print_usage () {
    local line
    while read -r line; do
        [[ $line =~ ^##\ ?(.*)$ ]] &&
            printf '%s\n' "${BASH_REMATCH[1]/\$0/$SCRIPT}"
    done < "${BASH_SOURCE[0]}"
}

print_version () {
    local line
    while read -r line; do
        [[ $line =~ ^#\ Version:\ *(.*)$ ]] &&
            printf '%s %s\n' "$SCRIPT" "${BASH_REMATCH[1]}"
    done < "${BASH_SOURCE[0]}"
}

main () {
    process_args "$@"

    ensure_tasks_dir

    [[ -n $DESC ]] && {
        create_issue
        exit 0
    }

    get_tasks

    [[ -n $OPEN ]] && {
        open_task $OPEN
        exit 0
    }

    list_tasks
}

process_args () {
    local positional_args=()

    local i
    for (( i=1; i <= $#; i++ )); {
        case ${!i} in
            -h|--help)
                print_usage
                exit 0
                ;;
            -v|--version)
                print_version
                exit 0
                ;;
            -n|--new)
                ((i++))
                DESC=${!i}
                [[ -n "$DESC" ]] || {
                    print_usage
                    exit 1
                }
                ;;
            -a|--all)
                ALL_TASKS=TRUE
                ;;
            -o|--open)
                ((i++))
                OPEN=${!i}
                [[ -n "$OPEN" ]] || {
                    print_usage
                    exit 1
                }
                ;;
            -*)
                local arg
                arg="${!i##*-}"
                arg="${!i%%=*}"
                printf '%s: invalid option -- %s\n' "$SCRIPT" "'$arg'"
                printf 'Try %s for more information.\n' "'$SCRIPT --help'"
                exit 1
                ;;
            *)
                positional_args+=("${!i}") # save positional args
                ;;
        esac
    }

    # Restore positional args
    set -- "${positional_args[@]}"

    BASE_DIR="${1:-.}"
    BASE_DIR="${BASE_DIR%%/*}"
}

ensure_tasks_dir() {
    TASKS_DIR="$BASE_DIR/tasks"
    [[ -d "$TASKS_DIR" ]] || {
        printf 'Could not find tasks directory %s\n' "'$TASKS_DIR'"
        exit 1
    }
}

create_issue() {
    local timestamp datestamp
    timestamp="$(date +'%Y%m%d-%H%M%S')"
    datestamp="$(date +'%B %d, %Y')"

    cat > "$TASKS_DIR/$timestamp.md" << EOF
# $DESC

- Created:  $datestamp
- Status:   OPEN
EOF

    printf 'Created issue %s\n' "'$timestamp.md'"
}

get_tasks() {
    declare -aG TASKS

    local task task_status
    while read -r task; do
        task_status=$(awk '/Status:/ {print $3}' "$TASKS_DIR/$task")
        [[ $task_status == OPEN || -n $ALL_TASKS ]] && TASKS+=($task)
    done <<< "$(ls -1r "$TASKS_DIR")"
}

list_tasks() {
    local task task_status task_desc task_color
    local i=1
    for task in ${TASKS[@]}; {
        task_desc="$(head -n 1 "$TASKS_DIR/$task")"
        task_desc="${task_desc:2}"

        task_status=$(awk '/Status:/ {print $3}' "$TASKS_DIR/$task")
        case $task_status in
            OPEN) task_color=2 ;;
            *)    task_color=5 ;;
        esac

        print_color 6; printf ' %d ' "$i"
        print_color $task_color; printf '%s' "$task"
        print_reset; printf ': %s\n' "$task_desc"

        ((i++))
    }
}

open_task() {
    local task
    local index=$1
    local i=1
    for task in ${TASKS[@]}; {
        (( index == i )) && {
            [[ -n $EDITOR ]] || {
                printf 'No $EDITOR variable is set.\n'
                exit 1
            }
            printf '%s/%s' "$TASKS_DIR" "$task" | xargs -o "$EDITOR"
            break
        }

        ((i++))
    }
}

print_color() {
    printf '\e[38;5;%dm' "$1"
}

print_reset () {
    printf '\e[m'
}

main "$@"
