#!/usr/bin/env bash

# (Is)sue (Li)ster :: 'isli'
# A script for tracking issues

# Maintainer:       Ben Buchanan
# Version:          1.0.0
# Last Modified:    08-Jun-2026

## Track issues in the terminal
##
## Usage: $0 [OPTIONS] [BASE_DIR]
##
## Options:
##   -h, --help                 Show this usage output
##   -v, --version              Show the version of the script
##   -n <DESC>, --new <DESC>    Create a new issue with description <DESC>
##   -a, --all                  List all tasks, regardless of status

# TODO: Print the tasks with indices, and add an option to open a task with a
#       specific index. This should use the $EDITOR environment variable, or
#       complain if it is unset.

SCRIPT="${BASH_SOURCE[0]##*/}"

print_usage () {
    local line
    while read -r line; do
        [[ $line =~ ^##\ ?(.*)$ ]] &&
            printf '%s\n' "${BASH_REMATCH[1]/\$0/$SCRIPT}"
    done < "${BASH_SOURCE[0]}"
}

print_version () {
    local line
    while read -r line; do
        [[ $line =~ ^#\ Version:\ *(.*)$ ]] &&
            printf '%s %s\n' "$SCRIPT" "${BASH_REMATCH[1]}"
    done < "${BASH_SOURCE[0]}"
}

main () {
    process_args "$@"

    ensure_tasks_dir

    [[ -n $DESC ]] && {
        create_issue
        exit 0
    }

    list_tasks
}

process_args () {
    local positional_args=()

    local i
    for (( i=1; i <= $#; i++ )); {
        case ${!i} in
            -h|--help)
                print_usage
                exit 0
                ;;
            -v|--version)
                print_version
                exit 0
                ;;
            -n|--new)
                ((i++))
                DESC=${!i}
                [[ -n "$DESC" ]] || {
                    print_usage
                    exit 1
                }
                ;;
            -a|--all)
                ALL_TASKS=TRUE
                ;;
            -*)
                local arg
                arg="${!i##*-}"
                arg="${!i%%=*}"
                printf '%s: invalid option -- %s\n' "$SCRIPT" "'$arg'"
                printf 'Try %s for more information.\n' "'$SCRIPT --help'"
                exit 1
                ;;
            *)
                positional_args+=("${!i}") # save positional args
                ;;
        esac
    }

    # Restore positional args
    set -- "${positional_args[@]}"

    BASE_DIR="${1:-.}"
    BASE_DIR="${BASE_DIR%%/*}"
}

ensure_tasks_dir() {
    TASKS_DIR="$BASE_DIR/tasks"
    [[ -d "$TASKS_DIR" ]] || {
        printf 'Could not find tasks directory %s\n' "'$TASKS_DIR'"
        exit 1
    }
}

create_issue() {
    local timestamp datestamp
    timestamp="$(date +'%Y%m%d-%H%M%S')"
    datestamp="$(date +'%B %d, %Y')"

    cat > "$TASKS_DIR/$timestamp.md" << EOF
# $DESC

- Created:  $datestamp
- Status:   OPEN
EOF

    printf 'Created issue %s\n' "'$timestamp.md'"
}

list_tasks() {
    local task task_status task_desc task_color
    while read -r task; do
        task_status=$(awk '/Status:/ {print $3}' "$TASKS_DIR/$task")
        [[ $task_status == OPEN || -n $ALL_TASKS ]] && {
            task_desc="$(head -n 1 "$TASKS_DIR/$task")"
            task_desc="${task_desc:2}"
            case $task_status in
                OPEN) task_color=2 ;;
                *)    task_color=5 ;;
            esac
            print_color $task_color
            printf '%s: ' "$task"
            print_reset
            printf '%s\n' "$task_desc"
        }
    done <<< "$(ls -1r "$TASKS_DIR")"
}

print_color() {
    printf '\e[38;5;%dm' "$1"
}

print_reset () {
    printf '\e[m'
}

main "$@"
