#!/usr/bin/env bash

# A script for connecting to the BU network via openconnect

# Maintainer:       Ben Buchanan
# Version:          2.0.1
# Last Modified:    03-Jun-2026

## Connect to the BU network via openconnect
##
## Usage: $0 [OPTIONS] <USERNAME>
##
## Options:
##   -h, --help     Show this usage output
##   -v, --version  Show the version of the script
##   -k, --kill     Close the VPN tunnel
##
##   <USERNAME>     The username you use to log in with CAS
##                  (You will be prompted for your password
##                  and 2FA token when invoked)

SCRIPT=${0##*/}
PROTOCOL=anyconnect
USERNAME=$1
SERVER=buvpn.binghamton.edu

OPENCONNECT_OPTS=(--protocol="$PROTOCOL" -u "$USERNAME" --passwd-on-stdin "$SERVER")

function printUsage() {
    while read -r line; do
        [[ $line =~ ^##\ ?(.*)$ ]] &&
            printf '%s\n' "${BASH_REMATCH[1]/\$0/$SCRIPT}"
    done < "${BASH_SOURCE[0]}"
}

printVersion () {
    while read -r line; do
        [[ $line =~ ^#\ Version:\ *(.*)$ ]] &&
            printf '%s %s\n' "$SCRIPT" "${BASH_REMATCH[1]}"
    done < "${BASH_SOURCE[0]}"
}

function killVPN() {
    if pkill openconnect > /dev/null 2>&1
    then
        dunstify "VPN ($SCRIPT)" "Disconnected from '$SERVER'"
    fi
    sleep 1
}

[ $# -ne 1 ] && { printUsage; exit; }

case $1 in
    -h|--help)
        printUsage;
        exit 0
        ;;
    -v|--version)
        printVersion;
        exit 0
        ;;
    -k|--kill)
        killVPN;
        exit 0
        ;;
esac

printf "Please enter the password for '%s': " "$USERNAME"
read -r -s PASSWD

printf "\nPlease enter your 2FA token: "
read -r TOKEN
printf "\n"

{ echo "$PASSWD"; echo "$TOKEN"; } | openconnect -q -b "${OPENCONNECT_OPTS[@]}"
sleep 1

tunnel="$(ip a | grep tun0)"
if [ -z "$tunnel" ]; then
    dunstify "VPN ($SCRIPT)" "Could not connect to '$SERVER'"
else
    dunstify "VPN ($SCRIPT)" "Connected to '$SERVER'"
fi
