#!/usr/bin/env bash

# Script for mounting the BU reports drive over the network

# Maintainer:       Ben Buchanan
# Version:          1.0.3
# Last Modified:    10-Jun-2026

die() {
    dunstify 'ERROR' "$1"
    exit 1
}

ENV_FILE="$HOME/.env.sh"
(( EUID == 0 )) && ENV_FILE="/.env.sh"

[[ -f "$ENV_FILE" ]] || die "Could not locate env file at '$ENV_FILE'"
# shellcheck disable=SC1090
source "$ENV_FILE"

REPORTS_MOUNT_DIR=/mnt/reports/
[[ -d $REPORTS_MOUNT_DIR ]] || die "Mountpoint '$REPORTS_MOUNT_DIR' does not exist"

mount "$BU_REPORTS_PATH" "$REPORTS_MOUNT_DIR" -o user="$BU_REPORTS_USER"
