#!/usr/bin/env bash

# A script to start polybar with a specified configuration

# Maintainer:       Ben Buchanan
# Version:          1.1.2
# Last Modified:    10-Jun-2026

die() {
    dunstify 'ERROR' "$1"
    exit 1
}

(( $# < 1 )) && die 'Please provide the name of the bar configuration'

BAR="$1"

reload_all_monitors() {
    local m orientation
	for m in $(xrandr --query | awk '/ connected/ {print $1}'); {
        orientation=$(xrandr -q --verbose | awk -v pattern="$m" \
            '$0 ~ pattern {sub("primary ", "", $0); print $5}')
        case $orientation in
            left|right) MONITOR=$m polybar --reload "$BAR-tiny" & ;;
            *)          MONITOR=$m polybar --reload "$BAR" & ;;
        esac
    }
}

# Kill all instances of polybar
killall -q polybar

# Wait until the processes have been properly shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

if type "xrandr"
then
    reload_all_monitors
else
	polybar --reload "$BAR" &
fi
