#!/usr/bin/env bash

# A script to start polybar with a specified configuration

# Maintainer:       Ben Buchanan
# Version:          1.1.1
# Last Modified:    03-Jun-2026

if [ $# -lt 1 ]
then
    dunstify 'Error' 'Please provide the name of the bar configuration'
    exit
fi

BAR="$1"

# Kill all instances of polybar
killall -q polybar

# Wait until the processes have been properly shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

if type "xrandr"
then
	for m in $(xrandr --query | awk '/ connected/ {print $1}')
    do
        orientation=$(xrandr -q --verbose | awk -v pattern="$m" '$0 ~ pattern {sub("primary ", "", $0); print $5}')
        case $orientation in
            left|right)
                MONITOR=$m polybar --reload "$BAR-tiny" &
                ;;
            *)
                MONITOR=$m polybar --reload "$BAR" &
                ;;
        esac
	done
else
	polybar --reload "$BAR" &
fi
