#!/usr/bin/env bash

# Select and apply a screen layout

# Maintainer:       Ben Buchanan
# Version:          2.1.1
# Last Modified:    10-Jun-2026

XRESOURCES=$HOME/.Xresources

FONT="Terminus-10"
BACKGROUND=$(awk '/background:/ {print $2}' "$XRESOURCES" | head -n 1)
FOREGROUND=$(awk '/color8:/ {print $2}' "$XRESOURCES")

DMENU_SETTINGS=(-nb "$BACKGROUND" -nf "$FOREGROUND" \
                -sb "$FOREGROUND" -sf "$BACKGROUND" \
                -fn "$FONT")

CURRENT_WALLPAPER=$HOME/Pictures/Wallpaper/wallpaper.jpg
GAPS_TOGGLE=$HOME/.config/polybar/gaps-toggle
STATUSBAR=polybar

[[ -f "$GAPS_TOGGLE" ]] || printf 'On' > "$GAPS_TOGGLE"

LAYOUT_DIR="$HOME/.config/mosaic/layouts"

DISPLAYS="$(xrandr | grep ' connected')"

die() {
    dunstify 'ERROR' "$1"
    exit 1
}

get_layouts() {
    LAYOUTS="$(ls -1 "$LAYOUT_DIR")"
    [[ -z "$LAYOUTS" ]] && die "Could not read layouts from '$LAYOUT_DIR'"
}

get_choice() {
    CHOICE="$(echo -e "\n$LAYOUTS" | dmenu -l 30 "${DMENU_SETTINGS[@]}" -i -p 'Choose a Layout:')"
    [[ -z "$CHOICE" ]] && exit 0
}

parse_xrandr_opts() {
    declare -aG XRANDR_OPTS

    local line output exists
    while read -r line; do
        [[ $line =~ ^output\ +(.*)$ ]] && {
            output="${BASH_REMATCH[1]}"
            exists="$(echo "$DISPLAYS" | grep "$output")"

            [[ -z $exists ]] && die "Could not detect display '$output'"

            XRANDR_OPTS+=("--output")
            XRANDR_OPTS+=("${BASH_REMATCH[1]}")
        }

        [[ $line =~ ^primary$ ]] && XRANDR_OPTS+=("--primary")
        [[ $line =~ ^mode\ +(.+x.+)$ ]] && {
            XRANDR_OPTS+=("--mode")
            XRANDR_OPTS+=("${BASH_REMATCH[1]}")
        }
        [[ $line =~ ^pos\ +(.+x.+)$ ]] && {
            XRANDR_OPTS+=("--pos")
            XRANDR_OPTS+=("${BASH_REMATCH[1]}")
        }
        [[ $line =~ ^rotate\ +(.+)$ ]] && {
            XRANDR_OPTS+=("--rotate")
            XRANDR_OPTS+=("${BASH_REMATCH[1]}")
        }
    done < "$LAYOUT_DIR/$CHOICE"
}

get_layouts
get_choice
parse_xrandr_opts

xrandr "${XRANDR_OPTS[@]}"

# Restart polybar on new layout
pkill $STATUSBAR
TOGGLE_STATE=$(cat "$GAPS_TOGGLE")
[[ "$TOGGLE_STATE" == "On" ]] && marquee gaps
[[ "$TOGGLE_STATE" == "Off" ]] && marquee no-gaps

feh --bg-fill "$CURRENT_WALLPAPER"
