#!/usr/bin/env bash

# A script for storing current .Xresources colors in a colorscheme file

# Maintainer:       Ben Buchanan
# Version:          1.0.0
# Last Modified:    23-Feb-2024

XRESOURCES=$HOME/.Xresources

FONT="xos4Terminus-10"
BACKGROUND=$(awk '/color0:/ {print $2}' "$XRESOURCES")
FOREGROUND=$(awk '/color4:/ {print $2}' "$XRESOURCES")

DMENU_SETTINGS=(-nb "$BACKGROUND" -nf "$FOREGROUND" \
                -sb "$FOREGROUND" -sf "$BACKGROUND" \
                -fn "$FONT")

SCHEME_DIR="$HOME/.config/colorschemes"

getColors() {
    CONTENT="$(head -n 37 "$XRESOURCES")"
    if [ -z "$CONTENT" ]; then
        notify-send "ERROR WHEN SAVING SCHEME" "Could not read $XRESOURCES!"
        exit
    fi
}

getSchemes() {
    SCHEMES="$(ls -1 "$SCHEME_DIR")"
    if [ -z "$SCHEMES" ]; then
        notify-send "ERROR WHEN SAVING SCHEME" "Could not read schemes from $SCHEME_DIR!"
        exit
    fi
}

getFilename() {
    FILENAME="$(echo -e "\n$SCHEMES" | dmenu -c -l 20 "${DMENU_SETTINGS[@]}" -i -p 'Scheme Name:')"
    if [ -z "$FILENAME" ]; then
        notify-send "ERROR WHEN SAVING SCHEME" "User did not provide a scheme name!"
        exit
    fi
}

saveColors() {
    MATCHES="$(echo -e "$SCHEMES" | grep "$FILENAME")"
    if [ -z "$MATCHES" ]; then
        echo -e "$CONTENT" > "$SCHEME_DIR/$FILENAME"
    else
        notify-send "ERROR WHEN SAVING SCHEME" "Colorscheme $FILENAME already exists!"
    fi
}

getColors
getSchemes
getFilename
saveColors
