#!/usr/bin/env bash

# A script that prints VPN status for polybar

# Maintainer:       Ben Buchanan
# Version:          1.0.1
# Last Modified:    01-Jun-2026

XRESOURCES=$HOME/.Xresources

VPN_INTERFACE=tun0

FOREGROUND=$(awk '/color6:/ {print $2}' "$XRESOURCES")
NORMAL=$(awk '/color7:/ {print $2}' "$XRESOURCES")

tunnel="$(ip a | grep "$VPN_INTERFACE")"

[[ -n "$tunnel" ]] && printf '(%%{F%s}VPN%%{F%s})' "$FOREGROUND" "$NORMAL"
