#!/usr/bin/env bash

# A master script for recoloring applications

# Maintainer:       Ben Buchanan
# Version:          1.1.0
# Last Modified:    09-Jun-2026

XRESOURCES=$HOME/.Xresources
DUNST_CONFIG=$HOME/.config/dunst/dunstrc
POLYBAR_CONFIG=$HOME/.config/polybar/config
ZATHURA_CONFIG=$HOME/.config/zathura/zathurarc

xrdb load "$XRESOURCES"

pkill dunst

get_colors () {
    BACKGROUND=$(awk '/background:/ {print $2}' "$XRESOURCES" | head -n 1)
    FOREGROUND=$(awk '/foreground:/ {print $2}' "$XRESOURCES")

    BACKGROUND_NO_HASH=${BACKGROUND//#/}

    RED=$(awk '/color1:/ {print $2}' "$XRESOURCES")
    GREEN=$(awk '/color2:/ {print $2}' "$XRESOURCES")
    YELLOW=$(awk '/color3:/ {print $2}' "$XRESOURCES")
}

gen_dunst () {
    sed -i --follow-symlinks -E \
        "s/background = \"#[0-9a-z]+\"/background = \"$BACKGROUND\"/" "$DUNST_CONFIG"
    sed -i --follow-symlinks -E \
        "s/foreground = \"#[0-9a-z]+\"/foreground = \"$FOREGROUND\"/" "$DUNST_CONFIG"
    sed -i --follow-symlinks -E \
        "s/frame_color = \"#[0-9a-z]+\"/frame_color = \"$GREEN\"/" "$DUNST_CONFIG"
}

gen_polybar () {
    sed -i --follow-symlinks -E \
        "s/black = #c0[0-9a-z]+/black = #c0$BACKGROUND_NO_HASH/" "$POLYBAR_CONFIG"
    sed -i --follow-symlinks -E \
        "s/invisible = #00[0-9a-z]+/invisible = #00$BACKGROUND_NO_HASH/" "$POLYBAR_CONFIG"
}

gen_zathura () {
    local pattern replace

    pattern='default-fg .*'; replace="default-fg \\\\$BACKGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"
    pattern='default-bg .*'; replace="default-bg \\\\$BACKGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"

    pattern='statusbar-fg .*'; replace="statusbar-fg \\\\$BACKGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"
    pattern='statusbar-bg .*'; replace="statusbar-bg \\\\$GREEN"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"

    pattern='inputbar-fg .*'; replace="inputbar-fg \\\\$GREEN"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"
    pattern='inputbar-bg .*'; replace="inputbar-bg \\\\$BACKGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"

    pattern='completion-fg .*'; replace="completion-fg \\\\$FOREGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"
    pattern='completion-bg .*'; replace="completion-bg \\\\$BACKGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"
    pattern='completion-group-fg .*'; replace="completion-group-fg \\\\$BACKGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"
    pattern='completion-group-bg .*'; replace="completion-group-bg \\\\$RED"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"
    pattern='completion-highlight-fg .*'; replace="completion-highlight-fg \\\\$BACKGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"
    pattern='completion-highlight-bg .*'; replace="completion-highlight-bg \\\\$FOREGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"

    pattern='index-fg .*'; replace="index-fg \\\\$FOREGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"
    pattern='index-bg .*'; replace="index-bg \\\\$BACKGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"
    pattern='index-active-fg .*'; replace="index-active-fg \\\\$BACKGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"
    pattern='index-active-bg .*'; replace="index-active-bg \\\\$YELLOW"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"

    pattern='recolor-darkcolor .*'; replace="recolor-darkcolor \\\\$FOREGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"
    pattern='recolor-lightcolor .*'; replace="recolor-lightcolor \\\\$BACKGROUND"
    sed -i --follow-symlinks "s/$pattern/$replace/" "$ZATHURA_CONFIG"
}

get_colors

gen_dunst
gen_polybar
gen_zathura

i3-msg restart
