#!/usr/bin/env bash

# A script for previewing colorschemes in the terminal

# Maintainer:       Ben Buchanan
# Version:          1.0.0
# Last Modified:    04-Jun-2026

XRESOURCES=$HOME/.Xresources

SCHEME_DIR=$HOME/.config/colorschemes
SCHEMES=()
MAX_SCHEME_LENGTH=12
BASE_WINDOW_SIZE=20
WINDOW_SIZE=$BASE_WINDOW_SIZE
WINDOW_MIN=0
WINDOW_MAX=$WINDOW_SIZE
INDEX=0

NO_FORMAT='\e[m'
BOLD='\e[1m'
HIGHLIGHT='\e[7m'

main () {
    (( BASH_VERSINFO[0] > 3 )) &&
        read_flags=(-t 0.05)

    get_colors "$XRESOURCES"
    get_schemes

    trap 'reset_terminal' EXIT
    trap 'get_term_size; clear_screen; redraw' WINCH

    get_term_size
    setup_terminal
    # TODO: We should have a draw_all here, then draw things individually
    # when a certain event happens. For example, when the user moves the
    # schemes window bounds, we clear the schemes box. When the user changes
    # the example code, we clear the example code box, etc.
    redraw

    # Vintage infinite loop
    for ((;;)); {
        read "${read_flags[@]}" -srn 1 && key "$REPLY"

        # Exit if there is no longer a terminal attached
        [[ -t 1 ]] || exit 1
    }
}

get_schemes() {
    [[ -d "$SCHEME_DIR" ]] || {
        printf 'Could not read schemes from %s\n' "'$SCHEME_DIR'"
        exit 1
    }
    mapfile -t SCHEMES < <(ls -1 "$SCHEME_DIR")
    NUM_SCHEMES=${#SCHEMES[@]}
    (( NUM_SCHEMES < 1 )) && {
        printf 'No schemes available to read\n'
        exit 0
    }
    for scheme in "${SCHEMES[@]}"; {
        (( ${#scheme} > MAX_SCHEME_LENGTH )) && {
            MAX_SCHEME_LENGTH=${#scheme}
        }
    }
}

get_colors() {
    FOREGROUND=$(awk '/foreground:/ {print $2}' "$1")
    BACKGROUND=$(awk '/background:/ {print $2}' "$1" | head -n 1)
    OPACITY=$(awk '/background:/ {print $2}' "$1" | tail -n 1)

    COLOR0=$(awk '/color0:/ {print $2}' "$1")
    COLOR1=$(awk '/color1:/ {print $2}' "$1")
    COLOR2=$(awk '/color2:/ {print $2}' "$1")
    COLOR3=$(awk '/color3:/ {print $2}' "$1")
    COLOR4=$(awk '/color4:/ {print $2}' "$1")
    COLOR5=$(awk '/color5:/ {print $2}' "$1")
    COLOR6=$(awk '/color6:/ {print $2}' "$1")
    COLOR7=$(awk '/color7:/ {print $2}' "$1")

    COLOR8=$(awk '/color8:/ {print $2}' "$1")
    COLOR9=$(awk '/color9:/ {print $2}' "$1")
    COLOR10=$(awk '/color10:/ {print $2}' "$1")
    COLOR11=$(awk '/color11:/ {print $2}' "$1")
    COLOR12=$(awk '/color12:/ {print $2}' "$1")
    COLOR13=$(awk '/color13:/ {print $2}' "$1")
    COLOR14=$(awk '/color14:/ {print $2}' "$1")
    COLOR15=$(awk '/color15:/ {print $2}' "$1")
}

set_colors() {
    printf '\33]10;%s\007' "$FOREGROUND"
    printf '\33]11;%s\007' "$BACKGROUND"
    printf '\33]708;%s\007' "$BACKGROUND"

    printf '\33]11;%s\007' "$OPACITY"
    printf '\33]708;%s\007' "$OPACITY"

    printf '\33]4;0;%s\007' "$COLOR0"
    printf '\33]4;1;%s\007' "$COLOR1"
    printf '\33]4;2;%s\007' "$COLOR2"
    printf '\33]4;3;%s\007' "$COLOR3"
    printf '\33]4;4;%s\007' "$COLOR4"
    printf '\33]4;5;%s\007' "$COLOR5"
    printf '\33]4;6;%s\007' "$COLOR6"
    printf '\33]4;7;%s\007' "$COLOR7"

    printf '\33]4;8;%s\007' "$COLOR8"
    printf '\33]4;9;%s\007' "$COLOR9"
    printf '\33]4;10;%s\007' "$COLOR10"
    printf '\33]4;11;%s\007' "$COLOR11"
    printf '\33]4;12;%s\007' "$COLOR12"
    printf '\33]4;13;%s\007' "$COLOR13"
    printf '\33]4;14;%s\007' "$COLOR14"
    printf '\33]4;15;%s\007' "$COLOR15"
}

setup_terminal () {
    save_cursor_position
    use_alt_screen_buffer
    disable_line_wrapping
    hide_cursor
    clear_screen

    # Hide echoing of user input
    stty -echo
}

reset_terminal () {
    get_colors "$XRESOURCES"
    set_colors

    enable_line_wrapping
    show_cursor
    clear_screen
    use_main_screen_buffer
    restore_cursor_position

    # Show user input
    stty echo
}

get_term_size () {
    shopt -s checkwinsize; (:;:)
}

redraw () {
    clamp_scheme_window

    draw_schemes
    draw_palette
    draw_example_code

    set_colors
}

clear_box() {
    local x=$1 y=$2
    local width=$(($3 + 2)) height=$(($4 + 3))

    for (( i=0; i < width; i++ )); {
        for (( j=0; j < height; j++ )); {
            move $((y + j)) $((x + i))
            printf ' '
        }
    }
}

draw_box() {
    local x=$1 y=$2
    local width=$(($3 + 2)) height=$(($4 + 3))
    local title=$5 title_color=$6

    local bar
    bar=$(printf '%*s' $width)
    bar=${bar// /─}

    move "$y" "$x"
    printf '┌%s┐' "$bar"
    move "$y" $((x + 2))
    set_modifiers "$BOLD"
    print_color "$title_color" '%s' "$title"
    reset_modifiers

    for (( i=1; i < height; i++ )); {
        move $((y + i)) "$x"
        printf '│'

        move $((y + i)) $((x + width + 1))
        printf '│'
    }

    move $height "$x"
    printf '└%s┘' "$bar"
}

draw_schemes() {
    # TODO: We only need to draw the box when its dimensions change
    draw_box 1 1 "$MAX_SCHEME_LENGTH" $WINDOW_SIZE 'COLORSCHEMES' 3

    local y=2
    for (( i=WINDOW_MIN; i <= WINDOW_MAX; i++ )); {
        local scheme=${SCHEMES[$i]}
        move $y 3
        [[ $INDEX -eq $i ]] && {
            get_colors "$SCHEME_DIR/$scheme"
            set_modifiers "$HIGHLIGHT"; set_modifiers "$BOLD"
        }
        printf '%s' "$scheme"
        [[ $INDEX -eq $i ]] && {
            reset_modifiers
        }
        y=$((y + 1))
    }

    local digits=${#NUM_SCHEMES}
    local pad="%Xd"
    pad="${pad//X/$digits}"

    move $y 3
    set_modifiers "$BOLD"
    print_color 1 "$pad" $((INDEX + 1))
    print_color 7 '/'
    print_color 4 '%d' "$NUM_SCHEMES"
    reset_modifiers
}

draw_palette() {
    # TODO: Magic numbers
    move 1 $((MAX_SCHEME_LENGTH + 15))
    set_modifiers "$BOLD"
    print_color 6 'PALETTE'
    reset_modifiers

    move 3 $((MAX_SCHEME_LENGTH + 6))
    printf 'Foreground  '
    set_modifiers "$HIGHLIGHT"
    printf '   %s   ' "$FOREGROUND"
    reset_modifiers

    move 5 $((MAX_SCHEME_LENGTH + 6))
    printf 'Background     %s   ' "$BACKGROUND"

    draw_palette_line 0 "$COLOR0" "$COLOR8"
    draw_palette_line 1 "$COLOR1" "$COLOR9"
    draw_palette_line 2 "$COLOR2" "$COLOR10"
    draw_palette_line 3 "$COLOR3" "$COLOR11"
    draw_palette_line 4 "$COLOR4" "$COLOR12"
    draw_palette_line 5 "$COLOR5" "$COLOR13"
    draw_palette_line 6 "$COLOR6" "$COLOR14"
    draw_palette_line 7 "$COLOR7" "$COLOR15"
}

draw_palette_line() {
    # TODO: Magic numbers
    local mult=$((LINES < BASE_WINDOW_SIZE + 2 ? 1 : 2))
    local y=$(($1 * mult + 7))
    move $y $((MAX_SCHEME_LENGTH + 6))
    printf ' %d ' "$1"
    if [ "$1" -eq 0 ];
    then
        printf '\33[37;40m %s ' "$2"
    else
        set_modifiers "$HIGHLIGHT"
        print_color "$1" ' %s ' "$2"
    fi
    reset_modifiers
    printf ' %2d ' $(($1 + 8))
    set_modifiers "$HIGHLIGHT"
    print_color $(($1 + 8)) ' %s ' "$3"
    reset_modifiers
}

draw_example_code() {
    # TODO: Instead of hard coding it here, put the example code in separate
    # files, parse them at runtime to determine the colors and modifiers.

    # TODO: Magic numbers
    local x=$((MAX_SCHEME_LENGTH + 32))
    local width=$((COLUMNS - x))

    draw_box $x 1 $width $WINDOW_SIZE 'EXAMPLE CODE' 2

    x=$((x + 2))
    move 3 $x
    print_color 5 '#include '
    print_color 6 '<stdio.h>'
    move 5 $x
    print_color 5 '#define '
    print_color 3 'HELLO_WORLD '
    print_color 6 '"Hello, world!"'
    move 7 $x
    set_modifiers "$BOLD"
    print_color 2 'int '
    reset_modifiers
    printf 'main('
    set_modifiers "$BOLD"
    print_color 2 'int '
    reset_modifiers
    printf 'argc, '
    set_modifiers "$BOLD"
    print_color 2 'char '
    reset_modifiers
    printf '** argv) {'
    x=$((x + 4))
    move 8 $x
    print_color 8 '// Print hello world message'
    reset_modifiers
    move 9 $x
    printf 'printf(HELLO_WORLD);'
    move 11 $x
    set_modifiers "$BOLD"
    print_color 1 'return '
    reset_modifiers
    print_color 6 '0'
    reset_modifiers
    x=$((x - 4))
    move 12 $x
    printf '}'
}

save_cursor_position () {
    printf '\e[s'
}

restore_cursor_position () {
    printf '\e[u'
}

use_alt_screen_buffer () {
    printf '\e[?1049h'
}

use_main_screen_buffer () {
    printf '\e[?1049l'
}

disable_line_wrapping () {
    printf '\e[?7l'
}

enable_line_wrapping () {
    printf '\e[?7h'
}

hide_cursor () {
    printf '\e[?25l'
}

show_cursor () {
    printf '\e[?25h'
}

move () {
    printf '\e[%d;%dH' "$1" "$2"
}

erase_up () {
    printf '\e[1J'
}

erase_all () {
    printf '\e[2J'
}

clear_screen () {
    move "$LINES" "$COLUMNS"
    erase_up
    [[ -v "$TMUX" ]] && erase_all # Fix for tmux
    move 0 0
}

set_modifiers () {
    printf '%b' "$1"
}

reset_modifiers () {
    printf '%b' "$NO_FORMAT"
}

print_color() {
    printf '\e[38;5;%dm' "$1"
    # TODO: We don't want this in here
    # shellcheck disable=SC2059
    printf "$2" "$3"
}

key () {
    # Handle special key presses
    [[ $1 == $'\e' ]] && {
        read "${read_flags[@]}" -rsn 2

        # Handle a normal escape key press
        [[ ${1}${REPLY} == $'\e\e['* ]] &&
            read "${read_flags[@]}" -rsn 1 _

        local special_key=${1}${REPLY}
    }

    case ${special_key:-$1} in
        # '\e'              :: Escape
        q|$'\e')
            exit
            ;;
        j)
            (( INDEX < NUM_SCHEMES - 1 )) && {
                INDEX=$((INDEX + 1))
                redraw
            }
            ;;
        J)
            (( INDEX < NUM_SCHEMES - 1)) && {
                INDEX=$((INDEX + 5))
                (( INDEX >= NUM_SCHEMES )) && {
                    INDEX=$((NUM_SCHEMES - 1))
                }
                redraw
            }
            ;;
        k)
            (( INDEX > 0 )) && {
                INDEX=$((INDEX - 1))
                redraw
            }
            ;;
        K)
            (( INDEX > 0 )) && {
                INDEX=$((INDEX - 5))
                (( INDEX < 0 )) && {
                    INDEX=0
                }
                redraw
            }
            ;;
        g)
            INDEX=0
            redraw
            ;;
        G)
            INDEX=$((NUM_SCHEMES - 1))
            redraw
            ;;
    esac

}

clamp_scheme_window() {
    # TODO: Magic numbers
    WINDOW_SIZE=$((LINES - 3 < BASE_WINDOW_SIZE ? LINES - 3 : BASE_WINDOW_SIZE))

    local gap=$((WINDOW_MAX - WINDOW_MIN))
    (( gap > WINDOW_SIZE )) && {
        WINDOW_MIN=0
        WINDOW_MAX=$WINDOW_SIZE
        INDEX=0
        clear_box 1 1 "$MAX_SCHEME_LENGTH" $WINDOW_SIZE
    }

    (( INDEX > WINDOW_MAX )) && {
        WINDOW_MAX=$INDEX
        WINDOW_MIN=$((WINDOW_MAX - WINDOW_SIZE))
        clear_box 1 1 "$MAX_SCHEME_LENGTH" $WINDOW_SIZE
    }

    (( INDEX < WINDOW_MIN )) && {
        WINDOW_MIN=$INDEX
        WINDOW_MAX=$((WINDOW_MIN + WINDOW_SIZE))
        clear_box 1 1 "$MAX_SCHEME_LENGTH" $WINDOW_SIZE
    }
}

main
