#!/usr/bin/env bash

# A script for previewing colorschemes in the terminal

# Maintainer:       Ben Buchanan
# Version:          1.2.1
# Last Modified:    06-Jun-2026

XRESOURCES=$HOME/.Xresources

SCHEME_DIR=$HOME/.config/colorschemes
SCHEMES=()
MAX_SCHEME_LENGTH=16
BASE_WINDOW_SIZE=20
WINDOW_SIZE=$BASE_WINDOW_SIZE
WINDOW_MIN=0
WINDOW_MAX=$((WINDOW_SIZE - 1))
INDEX=0

PALETTE_INDEX=0
SPECIAL_SELECT=

EXAMPLE_DIR="$HOME/.config/example_code"
EXAMPLES=()
EXAMPLE_INDEX=0

MODE=SCHEME

NO_FORMAT='\e[m'
BOLD='\e[1m'
UNDERLINE='\e[4m'
HIGHLIGHT='\e[7m'

main () {
    (( BASH_VERSINFO[0] > 3 )) && read_flags=(-t 0.05)

    get_colors "$XRESOURCES"
    get_schemes
    get_examples

    trap 'reset_terminal' EXIT
    trap 'get_term_size; redraw' WINCH

    get_term_size
    MAX_BUFFER_SIZE=$((COLUMNS / 2))
    setup_terminal
    redraw

    # Vintage infinite loop
    for ((;;)); {
        read "${read_flags[@]}" -srn 1 && key "$REPLY"

        # Exit if there is no longer a terminal attached
        [[ -t 1 ]] || exit 1
    }
}

get_schemes() {
    [[ -d "$SCHEME_DIR" ]] || {
        printf 'Could not read schemes from %s\n' "'$SCHEME_DIR'"
        exit 1
    }

    mapfile -t SCHEMES < <(ls -1 "$SCHEME_DIR")

    NUM_SCHEMES=${#SCHEMES[@]}
    (( NUM_SCHEMES < 1 )) && {
        printf 'No schemes available to read\n'
        exit 1
    }

    for scheme in "${SCHEMES[@]}"; {
        (( ${#scheme} > MAX_SCHEME_LENGTH )) && MAX_SCHEME_LENGTH=${#scheme}
    }
}

get_examples() {
    [[ -d "$EXAMPLE_DIR" ]] || {
        printf 'Could not read examples from %s\n' "'$EXAMPLE_DIR'"
        exit 1
    }

    mapfile -t EXAMPLES < <(ls -1 "$EXAMPLE_DIR")

    NUM_EXAMPLES=${#EXAMPLES[@]}
    (( NUM_EXAMPLES < 1 )) && {
        printf 'No examples available to read\n'
        exit 1
    }
}

get_colors() {
    FOREGROUND=$(awk '/foreground:/ {print $2}' "$1")
    case $1 in
        "$XRESOURCES")
            BACKGROUND=$(awk '/background:/ {print $2}' "$1" | head -n 1)
            OPACITY=$(awk '/background:/ {print $2}' "$1" | tail -n 1)
            ;;
        *)
            BACKGROUND=$(awk '/background:/ {print $2}' "$1")
            OPACITY=$(awk '/opacity:/ {print $2}' "$1")
            ;;
    esac

    declare -aG COLORS

    local i
    for i in {0..15}; {
        COLORS[i]=$(awk -v num="color$i:" '$0 ~ num {print $2}' "$1")
    }
}

set_colors() {
    printf '\33]10;%s\007' "$FOREGROUND"
    printf '\33]11;%s\007' "$BACKGROUND"
    printf '\33]708;%s\007' "$BACKGROUND"

    printf '\33]11;%s\007' "$OPACITY"
    printf '\33]708;%s\007' "$OPACITY"

    local i color_command
    for i in {0..15}; {
        printf -v color_command '\33]4;%d;%s\007' "$i" "${COLORS[$i]}"
        printf '%s' "$color_command"
    }
}

setup_terminal () {
    save_cursor_position
    use_alt_screen_buffer
    disable_line_wrapping
    hide_cursor
    clear_screen

    # Hide echoing of user input
    stty -echo
}

reset_terminal () {
    get_colors "$XRESOURCES"
    set_colors

    enable_line_wrapping
    show_cursor
    clear_screen
    use_main_screen_buffer
    restore_cursor_position

    # Show user input
    stty echo
}

get_term_size () {
    shopt -s checkwinsize; (:;:)
}

redraw () {
    clamp_scheme_window
    clear_screen

    local width=$((MAX_SCHEME_LENGTH + 4)) # Box borders plus gap
    HEIGHT=$((WINDOW_SIZE + 2)) # Box borders
    draw_box 1 1 $width $HEIGHT 'COLORSCHEMES' 2
    draw_schemes

    draw_palette
    draw_example_code

    draw_statusbar
    draw_keybindings
}

clear_box() {
    local x=$1 y=$2
    local width=$3 height=$4

    local i j
    for (( i=0; i < width; i++ )); {
        for (( j=0; j < height; j++ )); {
            move $((y + j)) $((x + i))
            printf ' '
        }
    }
}

draw_box() {
    local x=$1 y=$2
    local width=$3 height=$4
    local title=$5 title_color=$6

    local h_width=$((width - 2)) # Minus corners
    local bar
    printf -v bar '%*s' "$h_width" " "
    bar=${bar// /─}

    move "$y" "$x"
    printf '┌%s┐' "$bar"
    move "$y" $((x + 2))
    set_modifiers "$BOLD"
    print_color "$title_color"
    printf '%s' "$title"
    reset_modifiers

    local i
    for (( i=1; i < height; i++ )); {
        move $((y + i)) "$x"
        printf '│'

        move $((y + i)) $((x + width - 1))
        printf '│'
    }

    move "$height" "$x"
    printf '└%s┘' "$bar"
}

draw_schemes() {
    clamp_scheme_window

    local y=2
    local i
    for (( i=WINDOW_MIN; i <= WINDOW_MAX; i++ )); {
        local scheme=${SCHEMES[$i]}
        move $y 3
        [[ $INDEX -eq $i ]] && {
            get_colors "$SCHEME_DIR/$scheme"
            [[ $MODE == SCHEME ]] && {
                set_modifiers "$HIGHLIGHT"
                set_modifiers "$BOLD"
            }
        }
        printf '%s' "$scheme"
        [[ $INDEX -eq $i ]] && reset_modifiers
        y=$((y + 1))
    }

    set_colors

    local adjusted_index=$((INDEX + 1))
    local max_digits=${#NUM_SCHEMES}
    local curr_digits=${#adjusted_index}
    local digit_diff=$((max_digits - curr_digits))

    move $HEIGHT 3
    set_modifiers "$BOLD"
    print_color 1
    for (( i=0; i < digit_diff; i++)); {
        printf ' '
    }
    printf '%d' $adjusted_index
    print_color 7
    printf '/'
    print_color 4
    printf '%d' "$NUM_SCHEMES"
    reset_modifiers
}

draw_palette() {
    PALETTE_WIDTH=25
    PALETTE_MAX=22
    PALETTE_HEIGHT=$((HEIGHT < PALETTE_MAX ? HEIGHT : PALETTE_MAX))
    # Scheme borders, scheme gaps, outer gap, plus 1 = 6
    PALETTE_X=$((MAX_SCHEME_LENGTH + 6))
    local title='PALETTE'

    move 1 $((PALETTE_X + PALETTE_WIDTH / 2 - ${#title} / 2))
    set_modifiers "$BOLD"
    print_color 6
    printf '%s' "$title"
    reset_modifiers

    move 3 $PALETTE_X
    [[ $SPECIAL_SELECT == FG ]] && print_color 1
    printf 'Foreground  '
    reset_modifiers
    set_modifiers "$HIGHLIGHT"
    printf '   %s   ' "$FOREGROUND"
    reset_modifiers

    local bg_y=$((PALETTE_HEIGHT < PALETTE_MAX ? 4 : 5))
    move $bg_y $PALETTE_X
    [[ $SPECIAL_SELECT == BG ]] && print_color 1
    printf 'Background  '
    reset_modifiers
    printf '   %s   ' "$BACKGROUND"

    local i
    for i in {0..7}; {
        draw_palette_line "$i" "${COLORS[$i]}" "${COLORS[$((i + 8))]}"
    }
}

draw_palette_line() {
    local mult=$((PALETTE_HEIGHT < PALETTE_MAX ? 1 : 2))
    # Header, foreground/background lines, gaps
    local y_offset=$((PALETTE_HEIGHT < PALETTE_MAX ? 6 : 7))
    local y=$(($1 * mult + y_offset))
    move $y $PALETTE_X
    [[ -z $SPECIAL_SELECT && $MODE == PALETTE && $PALETTE_INDEX == "$1" ]] && print_color 1
    printf ' %d ' "$1"
    if [ "$1" -eq 0 ];
    then
        reset_modifiers
        printf '\33[40m %s ' "$2"
    else
        set_modifiers "$HIGHLIGHT"
        print_color "$1"
        printf ' %s ' "$2"
    fi
    reset_modifiers
    [[ -z $SPECIAL_SELECT && $MODE == PALETTE && $PALETTE_INDEX == $(($1 + 8)) ]] && print_color 1
    printf ' %2d ' $(($1 + 8))
    set_modifiers "$HIGHLIGHT"
    print_color $(($1 + 8))
    printf ' %s ' "$3"
    reset_modifiers
}

draw_example_code() {
    # TODO: Make more examples for other languages
    local x=$((PALETTE_X + PALETTE_WIDTH + 1)) # Plus gap
    local width=$((COLUMNS - x + 1)) # Account for gap

    # Minus borders and gap, then border
    clear_box $((x + 2)) 3 $((width - 3)) $((WINDOW_SIZE - 1))
    draw_box $x 1 $width $HEIGHT 'EXAMPLE CODE' 3

    local example=${EXAMPLES[$EXAMPLE_INDEX]}
    local lines
    mapfile -t lines < "$EXAMPLE_DIR/$example"

    x=$((x + 2)) # Box border and gap
    local y=3

    for line in "${lines[@]}"; {
        while [[ $line =~ ^.*%([0-9]+)%.*$ ]];
        do
            line="${line//%${BASH_REMATCH[1]}%/\\e[38;5;${BASH_REMATCH[1]}m}"
        done

        while [[ $line =~ ^.*@([0-9]+)@.*$ ]];
        do
            line="${line//@${BASH_REMATCH[1]}@/${BASH_REMATCH[1]}}"
        done

        line="${line//%HIGHLIGHT%/$HIGHLIGHT}"
        line="${line//%BOLD%/$BOLD}"
        line="${line//%UNDERLINE%/$UNDERLINE}"
        line="${line//%RESET%/$NO_FORMAT}"

        move $y $x
        printf '%b' "$line"
        y=$((y + 1))
    }

    move $HEIGHT $x
    printf 'File: '
    set_modifiers "$BOLD"
    print_color 5
    printf '%s' "$example"
    reset_modifiers
}

draw_statusbar() {
    local bar
    printf -v bar '%*s' $COLUMNS

    local mode_color
    [[ $MODE == SCHEME ]] && mode_color=2
    [[ $MODE == PALETTE ]] && mode_color=6
    [[ $MODE == EDIT ]] && mode_color=3

    local y=$((HEIGHT + 1))
    move $y 1
    clear_line
    set_modifiers "$HIGHLIGHT"
    set_modifiers "$BOLD"
    print_color $mode_color
    printf '%s' "$bar"
    move $y 2
    printf '%8s MODE │' "$MODE"
    [[ -n $PROMPT ]] && {
        printf ' %s: %s' "$PROMPT" "$EDIT_BUFFER"
    }
    reset_modifiers
}

draw_keybindings() {
    local y=$((HEIGHT + 2)) # Statusbar sits above
    move $y 1
    clear_line

    case $MODE in
        SCHEME)
            draw_keybinding 'j/k/J/K' 'Scroll'
            draw_keybinding 'g/G' 'Top/Bottom'
            draw_keybinding 'e' 'Cycle Example'
            draw_keybinding 'p' 'Palette Mode'
            draw_keybinding 'q/<ESC>' 'Quit'
            ;;
        PALETTE)
            draw_keybinding 'h/j/k/l' 'Color'
            draw_keybinding 'f/b' 'FG/BG'
            draw_keybinding '<ENTER>' 'Edit'
            draw_keybinding 'S' 'Save Scheme'
            draw_keybinding 'e' 'Cycle Example'
            draw_keybinding 's' 'Scheme Mode'
            draw_keybinding 'q/<ESC>' 'Quit'
            ;;
        EDIT)
            draw_keybinding '<ESC>' 'Palette Mode'
            draw_keybinding '<ENTER>' 'Confirm'
    esac
}

draw_keybinding() {
    set_modifiers "$BOLD"
    print_color 5
    printf '%s' "$1"
    reset_modifiers
    printf ': %s ' "$2"
}

save_cursor_position () {
    printf '\e[s'
}

restore_cursor_position () {
    printf '\e[u'
}

use_alt_screen_buffer () {
    printf '\e[?1049h'
}

use_main_screen_buffer () {
    printf '\e[?1049l'
}

disable_line_wrapping () {
    printf '\e[?7l'
}

enable_line_wrapping () {
    printf '\e[?7h'
}

hide_cursor () {
    printf '\e[?25l'
}

show_cursor () {
    printf '\e[?25h'
}

move () {
    printf '\e[%d;%dH' "$1" "$2"
}

erase_up () {
    printf '\e[1J'
}

erase_all () {
    printf '\e[2J'
}

clear_line () {
    printf '\e[0K'
}

clear_screen () {
    move "$LINES" "$COLUMNS"
    erase_up
    [[ -v "$TMUX" ]] && erase_all # Fix for tmux
    move 0 0
}

set_modifiers () {
    printf '%b' "$1"
}

reset_modifiers () {
    printf '%b' "$NO_FORMAT"
}

print_color() {
    printf '\e[38;5;%dm' "$1"
}

key () {
    # Handle special key presses
    [[ $1 == $'\e' ]] && {
        read "${read_flags[@]}" -rsn 2

        # Handle a normal escape key press
        [[ ${1}${REPLY} == $'\e\e['* ]] && read "${read_flags[@]}" -rsn 1 _

        local special_key=${1}${REPLY}
    }

    case $MODE in
        SCHEME)
            handle_scheme_mode_events "${special_key:-$1}"
            ;;
        PALETTE)
            handle_palette_mode_events "${special_key:-$1}"
            ;;
        EDIT)
            handle_edit_mode_events "${special_key:-$1}"
            ;;
    esac
}

handle_scheme_mode_events() {
    case $1 in
        # '\e' :: Escape
        q|$'\e')
            exit
            ;;
        j)
            (( INDEX < NUM_SCHEMES - 1 )) && INDEX=$((INDEX + 1))
            ;;
        J)
            (( INDEX < NUM_SCHEMES - 1)) && INDEX=$((INDEX + 5))
            (( INDEX >= NUM_SCHEMES )) && INDEX=$((NUM_SCHEMES - 1))
            ;;
        k)
            (( INDEX > 0 )) && INDEX=$((INDEX - 1))
            ;;
        K)
            (( INDEX > 0 )) && INDEX=$((INDEX - 5))
            (( INDEX < 0 )) && INDEX=0
            ;;
        g)
            INDEX=0
            ;;
        G)
            INDEX=$((NUM_SCHEMES - 1))
            ;;
        e)
            EXAMPLE_INDEX=$((EXAMPLE_INDEX + 1))
            (( EXAMPLE_INDEX >= NUM_EXAMPLES )) && EXAMPLE_INDEX=0
            ;;
        p)
            MODE=PALETTE
            ;;
    esac

    # Bulk handle different redraw events
    case $1 in
        j|J|k|K|g|G)
            draw_schemes
            draw_palette
            ;;
        e)
            draw_example_code
            ;;
        p)
            draw_schemes
            draw_palette
            draw_statusbar
            draw_keybindings
            ;;
    esac
}

handle_palette_mode_events() {
    case $1 in
        # '\e' :: Escape
        q|$'\e')
            exit
            ;;
        j)
            PALETTE_INDEX=$(((PALETTE_INDEX + 1) % 16))
            ;;
        k)
            PALETTE_INDEX=$(((PALETTE_INDEX + 15) % 16))
            ;;
        h|l)
            PALETTE_INDEX=$(((PALETTE_INDEX + 8) % 16))
            ;;
        f)
            if [ "$SPECIAL_SELECT" == FG ];
            then
                SPECIAL_SELECT=
            else
                SPECIAL_SELECT=FG
            fi
            ;;
        b)
            if [ "$SPECIAL_SELECT" == BG ];
            then
                SPECIAL_SELECT=
            else
                SPECIAL_SELECT=BG
            fi
            ;;
        e)
            EXAMPLE_INDEX=$((EXAMPLE_INDEX + 1))
            (( EXAMPLE_INDEX >= NUM_EXAMPLES )) && EXAMPLE_INDEX=0
            ;;
        s)
            MODE=SCHEME
            ;;
        S)
            MODE=EDIT
            EDIT_TYPE=SAVE
            PROMPT="Filename"
            EDIT_BUFFER="new-scheme"
            show_cursor
            ;;
        # '' :: Enter
        '')
            MODE=EDIT
            EDIT_TYPE=MODIFY
            case $SPECIAL_SELECT in
                FG)
                    PROMPT="Edit Foreground"
                    EDIT_BUFFER=$FOREGROUND
                    ;;
                BG)
                    PROMPT="Edit Background"
                    EDIT_BUFFER=$BACKGROUND
                    ;;
                *)
                    PROMPT="Edit Color $PALETTE_INDEX"
                    EDIT_BUFFER=${COLORS[$PALETTE_INDEX]}
                    ;;
            esac
            show_cursor
            ;;
    esac

    # Bulk handle different redraw events
    case $1 in
        h|j|k|l|f|b)
            draw_palette
            ;;
        e)
            draw_example_code
            ;;
        s)
            draw_schemes
            draw_palette
            draw_statusbar
            draw_keybindings
            ;;
        ''|S)
            # NOTE: The order here is important for cursor placement
            draw_keybindings
            draw_statusbar
            ;;
    esac
}

handle_edit_mode_events() {
    case $EDIT_TYPE in
        SAVE)
            handle_save_events "$1"
            ;;
        MODIFY)
            handle_modify_events "$1"
            ;;
    esac
}

handle_save_events() {
    case $1 in
        # '\e' :: Escape
        $'\e')
            MODE=PALETTE
            PROMPT=
            EDIT_BUFFER=
            hide_cursor
            ;;
        # '\177', '\b' :: Backspace
        [0-9a-zA-Z._]|' '|-|$'\177'|$'\b')
            edit_buffer_value "$1"
            ;;
        # '' :: Enter
        '')
            (( ${#EDIT_BUFFER} < 1 )) && return
            save_colorscheme
            get_schemes
            PROMPT=
            EDIT_BUFFER=
            MODE=PALETTE
            hide_cursor
            ;;
    esac

    # Bulk handle different redraw events
    case $1 in
        # '\e' :: Escape
        $'\e')
            draw_statusbar
            draw_keybindings
            ;;
        # '\177', '\b' :: Backspace
        [0-9a-zA-Z._]|' '|-|$'\177'|$'\b')
            draw_statusbar
            ;;
        # '' :: Enter
        '')
            set_colors
            clear_box 3 2 "$MAX_SCHEME_LENGTH" $WINDOW_SIZE
            draw_schemes
            draw_palette
            draw_statusbar
            draw_keybindings
            ;;
    esac
}

handle_modify_events() {
    case $1 in
        # '\e' :: Escape
        $'\e')
            MODE=PALETTE
            PROMPT=
            EDIT_BUFFER=
            hide_cursor
            ;;
        # '\177', '\b' :: Backspace
        [0-9a-f]|$'\177'|$'\b')
            edit_hex_value "$1"
            ;;
        # '' :: Enter
        '')
            (( ${#EDIT_BUFFER} != 7 )) && return
            case $SPECIAL_SELECT in
                FG)
                    FOREGROUND=$EDIT_BUFFER
                    ;;
                BG)
                    BACKGROUND=$EDIT_BUFFER
                    [[ $OPACITY =~ ^(\[[0-9]+\]).*$ ]]
                    OPACITY="${BASH_REMATCH[1]}$EDIT_BUFFER"
                    ;;
                *)
                    COLORS[PALETTE_INDEX]=$EDIT_BUFFER
                    ;;
            esac
            PROMPT=
            EDIT_BUFFER=
            MODE=PALETTE
            hide_cursor
            ;;
    esac

    # Bulk handle different redraw events
    case $1 in
        # '\e' :: Escape
        $'\e')
            draw_statusbar
            draw_keybindings
            ;;
        # '\177', '\b' :: Backspace
        [0-9a-f]|$'\177'|$'\b')
            draw_statusbar
            ;;
        # '' :: Enter
        '')
            set_colors
            draw_palette
            draw_statusbar
            draw_keybindings
            ;;
    esac
}

edit_buffer_value() {
    case $1 in
        [0-9a-zA-Z._]|' '|-)
            (( ${#EDIT_BUFFER} > MAX_BUFFER_SIZE )) && return
            EDIT_BUFFER="$EDIT_BUFFER$1"
            ;;
        # '\177', '\b' :: Backspace
        $'\177'|$'\b')
            (( ${#EDIT_BUFFER} <= 0 )) && return
            EDIT_BUFFER="${EDIT_BUFFER::-1}"
            ;;
    esac
}

edit_hex_value() {
    case $1 in
        [0-9a-f])
            (( ${#EDIT_BUFFER} > 6 )) && return
            EDIT_BUFFER="$EDIT_BUFFER$1"
            ;;
        # '\177', '\b' :: Backspace
        $'\177'|$'\b')
            (( ${#EDIT_BUFFER} <= 1 )) && return
            EDIT_BUFFER="${EDIT_BUFFER::-1}"
            ;;
    esac
}

clamp_scheme_window() {
    local normal_height=$((BASE_WINDOW_SIZE + 4)) # Borders, statusbar, keybindings
    # Account for box borders, statusbar, keybindings, and slack
    WINDOW_SIZE=$((LINES < normal_height ? LINES - 5 : BASE_WINDOW_SIZE))

    local gap=$((WINDOW_MAX - WINDOW_MIN))
    (( gap > WINDOW_SIZE )) && {
        WINDOW_MIN=0
        WINDOW_MAX=$((WINDOW_SIZE - 1))
        INDEX=0
        redraw
    }

    (( INDEX > WINDOW_MAX )) && {
        WINDOW_MAX=$INDEX
        WINDOW_MIN=$((WINDOW_MAX - gap))
        clear_box 3 2 "$MAX_SCHEME_LENGTH" $WINDOW_SIZE
    }

    (( INDEX < WINDOW_MIN )) && {
        WINDOW_MIN=$INDEX
        WINDOW_MAX=$((WINDOW_MIN + gap))
        clear_box 3 2 "$MAX_SCHEME_LENGTH" $WINDOW_SIZE
    }
}

save_colorscheme() {
    local base_filename="$SCHEME_DIR/$EDIT_BUFFER"
    local filename="$base_filename"
    local i=1
    while [ -f "$filename" ];
    do
        filename="$base_filename.$i"
        i=$((i + 1))
    done

    cat > "$filename" << EOF
foreground: $FOREGROUND
background: $BACKGROUND
opacity: $OPACITY
color0: ${COLORS[0]}
color1: ${COLORS[1]}
color2: ${COLORS[2]}
color3: ${COLORS[3]}
color4: ${COLORS[4]}
color5: ${COLORS[5]}
color6: ${COLORS[6]}
color7: ${COLORS[7]}
color8: ${COLORS[8]}
color9: ${COLORS[9]}
color10: ${COLORS[10]}
color11: ${COLORS[11]}
color12: ${COLORS[12]}
color13: ${COLORS[13]}
color14: ${COLORS[14]}
color15: ${COLORS[15]}
EOF
}

main
