#!/usr/bin/env bash

# A script for creating an OpenVPN tunnel using a .ovpn file

# Maintainer:       Ben Buchanan
# Version:          1.0.0
# Last Modified:    11-Sep-2024

## Create an OpenVPN tunnel using a .ovpn file
##
## Usage: $0 [OPTIONS] <FILE>
##
## Options:
##   -h, --help     Show this usage output
##   -v, --version  Show the version of the script
##   -k, --kill     Close the VPN tunnel
##
##   <FILE>         The .ovpn file for the server you want to connect to

SCRIPT=${0##*/}

function print_usage() {
    while read -r line; do
        [[ $line =~ ^##\ ?(.*)$ ]] &&
            printf '%s\n' "${BASH_REMATCH[1]/\$0/$SCRIPT}"
    done < "${BASH_SOURCE[0]}"
}

print_version () {
    while read -r line; do
        [[ $line =~ ^#\ Version:\ *(.*)$ ]] &&
            printf '%s %s\n' "$SCRIPT" "${BASH_REMATCH[1]}"
    done < "${BASH_SOURCE[0]}"
}

function kill_vpn() {
    if pkill openvpn > /dev/null 2>&1
    then
        notify-send "VPN ($SCRIPT)" 'Disconnected'
    fi
    sleep 1
}

[ $# -ne 1 ] && { print_usage; exit 1; }

case $1 in
    -h|--help)
        print_usage;
        exit 0
        ;;
    -v|--version)
        print_version;
        exit 0
        ;;
    -k|--kill)
        kill_vpn;
        exit 0
        ;;
esac

openvpn "$1" &

if ifconfig tun0 > /dev/null 2>&1
then
    notify-send "VPN ($SCRIPT)" "Connected via '$1'"
else
    notify-send "VPN ($SCRIPT)" 'Something went wrong!'
fi
