#!/usr/bin/env bash

# A script to turn squeezelite on and off

# Maintainer:       Ben Buchanan
# Version:          1.0.0
# Last Modified:    29-Feb-2024

ENV_FILE="$HOME/.env.sh"

if [ -f "$ENV_FILE" ]
then
    source "$ENV_FILE"
else
    notify-send 'Error' "Could not locate env file at '$ENV_FILE'"
    exit
fi

if ! pkill squeezelite
then
    squeezelite -s "$LMS_IP_ADDRESS" -n "$(hostname)" &
fi
