#!/usr/bin/env bash

# A script to turn squeezelite on and off

# Maintainer:       Ben Buchanan
# Version:          1.0.2
# Last Modified:    03-Jun-2026

if [ "$EUID" -ne 0 ]
then
    ENV_FILE="$HOME/.env.sh"
else
    ENV_FILE="/.env.sh"
fi

if [ -f "$ENV_FILE" ]
then
    source "$ENV_FILE"
else
    dunstify 'Error' "Could not locate env file at '$ENV_FILE'"
    exit
fi

if ! pkill squeezelite
then
    squeezelite -s "$LMS_IP_ADDRESS" -n "$(hostname)" &
fi
