#!/usr/bin/env bash

# A script for mounting/unmounting devices using dmenu

# Maintainer:       Ben Buchanan
# Version:          1.0.3
# Last Modified:    11-Jun-2026

XRESOURCES=$HOME/.Xresources

FONT="Terminus-10"
BACKGROUND=$(awk '/background:/ {print $2}' "$XRESOURCES" | head -n 1)
FOREGROUND=$(awk '/color4:/ {print $2}' "$XRESOURCES")

DMENU_SETTINGS=(-nb "$BACKGROUND" -nf "$FOREGROUND" \
                -sb "$FOREGROUND" -sf "$BACKGROUND" \
                -fn "$FONT")

die() {
    dunstify 'ERROR' "$1"
    exit 1
}

get_devices_by_label() {
    DEVICES="$(ls -1 /dev/disk/by-label/)"
    [[ -z "$DEVICES" ]] && die 'No labeled devices could be found.'
}

get_choice() {
    CHOICE="$(echo -e "\n$DEVICES" | dmenu -l 20 "${DMENU_SETTINGS[@]}" -i -p 'Choose a Device:')"
    [[ -z "$CHOICE" ]] && exit 0
}

get_devices_by_label
get_choice

# Attempt to mount the device; if it's already mounted, unmount it
if ! mount LABEL="$CHOICE"
then
    if ! umount LABEL="$CHOICE"
    then
        die "Something went wrong when mounting/unmounting device '$CHOICE'"
    else
        dunstify "Device $CHOICE unmounted"
    fi
else
    dunstify "Device $CHOICE mounted"
fi
