#!/usr/bin/env bash

# A script to handle backlight controls that give you any guff
# Basically, we just cop out and use xrandr instead

# Maintainer:       Ben Buchanan
# Version:          1.3.0
# Last Modified:    11-Jun-2026

OUTPUT_DEVICES=$(xrandr -q | awk '/ connected/ {print $1}')
BRIGHTNESS_FILE=$HOME/.config/torch-brightness

[[ -f "$BRIGHTNESS_FILE" ]] || printf '1.0' > "$BRIGHTNESS_FILE"

(( $# == 2 )) || {
    printf 'Usage: torch --[inc|dec] <percent>\n'
    exit 1
}

OPERATION=$1
PERCENT=$2

# Our math only works on percents >= 10
(( PERCENT >= 10 )) || {
    printf 'Percentage must be >= 10\n'
    exit 1
}

CURRENT_BRIGHTNESS=$(awk '{printf "%d\n", $1*100}' "$BRIGHTNESS_FILE")

case $OPERATION in
    --inc) NEW_BRIGHTNESS=$((CURRENT_BRIGHTNESS + PERCENT)) ;;
    --dec) NEW_BRIGHTNESS=$((CURRENT_BRIGHTNESS - PERCENT)) ;;
    --refresh) NEW_BRIGHTNESS=$CURRENT_BRIGHTNESS ;;
esac

(( NEW_BRIGHTNESS > 100 )) && exit 0
(( NEW_BRIGHTNESS < 5 )) && exit 0

XRANDR_FLOAT=$(echo "$NEW_BRIGHTNESS" | awk '{printf "%.1f\n", $1/100}')

for x in $OUTPUT_DEVICES; {
    xrandr --output "$x" --brightness "$XRANDR_FLOAT"
}

echo "$XRANDR_FLOAT" > "$BRIGHTNESS_FILE"
