#!/usr/bin/env bash

# Setup two 1920x1080 displays and a third vertical monitor with a statusbar

# Maintainer:       Ben Buchanan
# Version:          1.1.0
# Last Modified:    07-Jun-2024

# NOTE: This is very much hard-coded for my setup at work right now

GAPS_TOGGLE_FILE=$HOME/.toggle-util/gaps-toggle

xrandr --output eDP-1 --primary --mode 1920x1080 --pos 1920x300 --rotate normal \
       --output HDMI-1 --mode 1680x1050 --pos 3840x0 --rotate left \
       --output DP-2-2 --mode 1920x1080 --pos 0x300 --rotate normal

feh --bg-fill ~/Pictures/Wallpaper/wallpaper.jpg

pkill polybar

TOGGLE_STATE=$(cat "$GAPS_TOGGLE_FILE");
case "$TOGGLE_STATE" in
    "On")
        marquee gaps ;;
    "Off")
        marquee no-gaps ;;
    *)
        notify-send 'Error when toggling bar' "Invalid toggle state '$TOGGLE_STATE'";
        exit
        ;;
esac
