#!/usr/bin/env bash

# Setup two 1920x1080 displays and a third vertical monitor with a statusbar

# Maintainer:       Ben Buchanan
# Version:          1.1.1
# Last Modified:    07-Jun-2024

CURRENT_WALLPAPER=$HOME/Pictures/Wallpaper/wallpaper.jpg
GAPS_TOGGLE=$HOME/.toggle-util/gaps-toggle
STATUSBAR=polybar

# NOTE: I don't like hard-coding these, but it's easier for the moment
OUTPUT_DEVICE_1=eDP-1
OUTPUT_DEVICE_2=DP-2-2
OUTPUT_DEVICE_3=HDMI-1

XRANDR_OPTIONS_DISPLAY_1=(--output $OUTPUT_DEVICE_1 --primary --mode 1920x1080 --pos 1920x300 --rotate normal)
XRANDR_OPTIONS_DISPLAY_2=(--output $OUTPUT_DEVICE_2 --mode 1920x1080 --pos 0x300 --rotate normal)
XRANDR_OPTIONS_DISPLAY_3=(--output $OUTPUT_DEVICE_3 --mode 1680x1050 --pos 3840x0 --rotate left)

xrandr "${XRANDR_OPTIONS_DISPLAY_1[@]}" "${XRANDR_OPTIONS_DISPLAY_2[@]}" "${XRANDR_OPTIONS_DISPLAY_3[@]}"

# Restart polybar on new layout
pkill $STATUSBAR
TOGGLE_STATE=$(cat "$GAPS_TOGGLE")
[ "$TOGGLE_STATE" == "On" ] && marquee gaps
[ "$TOGGLE_STATE" == "Off" ] && marquee no-gaps

feh --bg-fill "$CURRENT_WALLPAPER"
