#!/usr/bin/env bash

# A custom locker using i3lock

# Maintainer:       Ben Buchanan
# Version:          1.0.1
# Last Modified:    11-Jun-2026

XRESOURCES=$HOME/.Xresources

# Set to one of the methods defined below, or define your own
LOCK_METHOD=color_fill

color_fill () {
    BACKGROUND=$(awk '/background:/ {print $2}' "$XRESOURCES" | head -n 1)
    i3lock -c "$BACKGROUND"
}

blur_screenshot () {
    # Take a screenshot
    scrot /tmp/current.png

    # Add blur to the screenshot
    convert -blur 0x4 /tmp/current.png /tmp/blur.png

    i3lock -i /tmp/blur.png
}

overlay_screenshot () {
    # Provide path to your desired overlay
    OVERLAY=/path/to/overlay.png

    [[ -f "$OVERLAY" ]] || {
        printf 'Provided overlay %s is not a file.\n' "'$OVERLAY'"
        exit 1
    }

    # Take a screenshot
    scrot /tmp/current.png

    # Add overlay to the screenshot
    composite -gravity southwest "$OVERLAY" /tmp/current.png /tmp/lock.png

    i3lock -i /tmp/lock.png
}

$LOCK_METHOD
