# Configuration file for bash

# Maintainer:       Ben Buchanan
# Version:          1.2.0
# Last Modified:    01-Jun-2026

# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !

# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]]; then
	# Shell is non-interactive.  Be done now!
	return
fi

# Custom shell prompt
PS1="[\[\e[33m\]\u\[\e[m\]@\[\e[31m\]\h\[\e[m\]] \[\e[34m\]\W\[\e[m\] \[\e[0m\]>\[\e[0m\]>\[\e[m\] \[\e0"

# Custom Git Tree command
git () {
    if [[ $@ == "tree" ]]; then
        command git log --oneline --decorate --graph --all
    else
        command git "$@"
    fi
}

# Handy helper for sourcing files
source_if_exists () {
    if test -r "$1"; then
        source "$1"
    fi
}

export EDITOR="vim"
export TERM="xterm-256color"

# $PATH Additions
export PATH="$HOME/.local/bin:$PATH"
export PATH="/sbin:/usr/sbin:$PATH"

# Ensure sudo can use our $PATH
alias sudo="sudo env "PATH=$PATH""

# Ensure ls uses colors
alias ls='ls --color=auto'

# Configuration for pfetch
export PF_INFO="ascii title os kernel host shell editor wm"

# Configuration for sapf
export SAPF_HISTORY="$HOME/.sapf-files/sapf-history.txt"
export SAPF_LOG="$HOME/.sapf-files/sapf-log.txt"
export SAPF_PRELUDE="$HOME/.sapf-files/sapf-prelude.txt"
export SAPF_EXAMPLES="$HOME/.sapf-files/sapf-examples.txt"
export SAPF_README="$HOME/.sapf-files/README.txt"
export SAPF_RECORDINGS="$HOME/.sapf-files/recordings"
export SAPF_SPECTROGRAMS="$HOME/.sapf-files/spectrograms"

# Any sensitive or machine-specific info goes into ~/.env.sh
source_if_exists "$HOME"/.env.sh

# Fix for urxvt geometry issues
[[ $(ps ho command $(ps ho ppid $$)) == 'urxvt' ]] && clear
[[ $(ps ho command $(ps ho ppid $$)) == 'x-terminal-emulator' ]] && clear
