#!/bin/bash

# A script to start polybar with a command line specified name (configuration)
# Maintainer: Ben Buchanan (https://github.com/Nynergy)

BAR="$1"

# Kill all instances of polybar
killall -q polybar

# Wait until the processes have been properly shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

if type "xrandr"; then
	for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
		MONITOR=$m polybar --reload "$BAR" &
	done
else
	polybar --reload "$BAR" &
fi
